### ISSUE TITLE
This should call back to a function in the gameboard class/file which pushes the location value to the ships beenHit array.... it runs in the tests, but doesn't run when called in the DOM scripts

### ISSUE THREAD

**Issue by dvonnew** [dvonnew/battleship#1]
https://github.com/dvonnew/battleship/blob/d74694ffc2a4ede0dfcfc624e5ed93c65ac22deb/src/DOM/DOMscripts.js#L31

**Comment by tylerphelan** [comment]
@dvonnew this space is kinda weird: https://github.com/dvonnew/battleship/blob/d74694ffc2a4ede0dfcfc624e5ed93c65ac22deb/src/index.js#L9
